### ISSUE TITLE
Problems using color sensors via Mindsensors EV3 Sensor MUX

### ISSUE THREAD

**Issue by zupanibla** [ev3dev/ev3dev#1048]
Hi,
me and my team are attending a national competition in robotics and are participating in the line following discipline. Since we started running out of ports we've decided to order a Mindsensors EV3 Sensor MUX to add a few extra color sensors to our robot.

We intend to use them for detecting green markings in the arena but they don't differentiate black and green colors in the COL-COLOR mode too well that's why we want to use the RAW-RGB mode.

I have noticed that the only modes that are available while using the sensors via a multiplexer are COL-REFLECT, COL-AMBIENT and COL-COLOR.

I was wondering whether this is a bug. If not is there any other way to obtain raw rgb values from a color sensor connected via mux?

**Comment by dlech** [comment]
The Mindsensors sensor mux firmware does not support the RAW-RGB mode. You will have to ask mindsensors.com to see if there is a possibility that they might add it. Otherwise, you will have to directly connect the sensors to use that mode. Another option might be to use the sensors via USB like [this](https://lechnology.com/2014/09/using-uart-sensors-on-any-linux/).
