### ISSUE TITLE
How to detect an undocumented sensor?

### ISSUE THREAD

**Issue by jlehuen** [ev3dev/ev3dev#1068]
Hello,
I wrote a driver for the - low documented - NumericPad from Mindsensor (solved issue #1049) but I have a new question : _How can I detect if a NumericPad is connected to a specific port?_

Thanks,
Jerome

**Comment by dlech** [comment]
Since this sensor doesn't follow the usual convention of having a vendor and product ID at registers 0x00 and 0x08, it will be hard to make a 100% positive identification. However, the default address of 0x5a is not used by any other MINDSTORMS compatible sensors that I know of. You could just try reading a byte from register 0x00 at that address. If there is no error, then it is pretty safe to assume that there is a keypad connected.

P.S. I'm guessing that when you say "I wrote a driver", that you don't mean a Linux kernel driver.

**Comment by jlehuen** [comment]
Thank you for the advice. Sure, the code I posted at the end of issue #1049 is not a Linux kernel driver, just a function to read the sensor's data, sorry for the inaccuracy.
Jerome

**Comment by jlehuen** [comment]
This code does the job, thank you :

~~~c
#include <fcntl.h>
#include <stdbool.h>
#include <linux/i2c-dev.h>
#include "smbus.h"

#define I2C_ADDR 0x5A // Unshifted 7 bits address (do not use 0xB4)
#define DATA_REG 0x00 // Data register

bool keypad_is_plugged(int port) {
	char filename[20];
	snprintf(filename, 19, "/dev/i2c-%d", port+2);
	int file = open(filename, O_RDWR);
	if (file < 0) return false;
	if (ioctl(file, I2C_SLAVE, I2C_ADDR) < 0) return false;
	if (i2c_smbus_read_byte_data(file, DATA_REG) < 0) return false;
	return true;
}
~~~
