### ISSUE TITLE
Doubling motor encoder precision

### ISSUE THREAD

**Issue by nutki** [ev3dev/ev3dev#148]
On the Wikipedia page for EV3 I found information that you can double position accuracy by enabling interrupt on both irq and dir lines of the encoder. So I looked in the ev3dev code to find out if this was implemented or possible to implement here.
So it seems that the position decoding mostly follows original Lego firmware. But it is not unfeasible to add the extra interrupt handling. This means twice as much interrupts from the encoder which may pose a problem (additional ~500Hz per motor). On the other hand the existing interrupt handler can be optimized so overall there would be more interrupts but with faster handling.
Here are some of my findings:
- There are two tables where maximum motor speed is represented: `CountsPerPulse` (which should be MaxClockTicksPer100Pulses really) and `MaxPulsesPerSec`. The values in the former are used for estimating speed and the latter is used to cap the regulation mode speed. That may be intentional but the speeds expressed with `MaxPulsesPerSec` are lower (150 vs 167rpm for L motor and 200 vs 230rpm for M).
- There is no way to get current `MaxPulsesPerSec` from user land, it seems. `pulses_per_second_sp` can be set to anything, but there is no feedback that it was capped.
- counts_per_pulse is always initialized to CountsPerPulse[MOTOR_TYPE_TACHO] regardless of the motor type, but as this is not used anymore to calculate speed percentage there it has only influence on estimated speed to get the numbers of samples to average when calculating speed and detecting stopped motor (less that 1% of that speed).
- Encoder irq has a shortcut for high speed to just assume no direction change, not looking at the other encoder line. I am not sure what is the purpose of this code. It does not seem to save much processing so maybe the reading of the direction line may be unreliable if the interrupt handler was too slow to trigger. Anyway this is dead code now as it relies on the `speed` variable which is not set anymore.
- There are some cycles wasted to cap dir_chg_samples, but it is not really necessary. It is only a problem when it actually overflows the 31 bits which would take 50days of full speed operation, and even then it would only cause brief (sub second) loss of speed reporting.
- There seems to be an off by one error when accessing tacho samples table (inherited form the Lego firmware). When dir_chg_samples is 1 we access 2 last samples (the other may come from long time ago or the opposite direction spin). But this seems not to be a problem. Which actually indicates that maintaining dir_chg_samples may not be needed at all.
- The calculation of speed `(33000000 * ev3_tm->samples_per_speed) / Diff` is dangerously close to overflow. `samples_per_speed` goes currently up to 64 with the potential to be up to 127 (because TACHO_SAMPLES is 128) and this expression overflows as 66. That suggests TACHO_SAMPLES could be lowered to 66 for smaller cache footprint of the irq handler.

I may work on some proof of concept implementation if you don't mind.

BTW, it is strange that Wikipedia takes a paragraph to describe this non usable extension (the code cannot be used as a drop in replacement because it loses speed calculation), but no mention of ev3dev (except for a link to python bindings which happen to use it).

**Comment by dlech** [comment]
I would like to revive this conversation, but for a different reason. I've been working on making BrickPi work with the changes from ev3dev/lego-linux-drivers#23. BrickPi uses this double motor encoder precision so that the LEGO motors have 720 counts per rotation. I have had to introduce a scaling factor to translate the "fixed" motor information such as count_per_rot and max_speed for BrickPi since it has twice the resolution as the EV3 with the same motors.

So do we leave in the scaling factor? Or do we implement the double precision in EV3 too? Or do we just count by twos in the EV3 driver so that count_per_rot is the same on all platforms?

**Comment by cho934** [comment]
I think it will be great to have this possibility of double precision on the EV3 too.

**Comment by rhempel** [comment]
I'm not sure there's much benefit in doubling the resolution when there is so much slop in the motors, and I also am concerned that the Firgelli linear encoders (that change state very slowly anyways) might introduce false counts.

Counting by 2s is fine, or we could have the BrickPi results divided by 2 :-)

The gold standard for capabilities should be LEGO motors on the EV3, but I'd be happy to hear someone else say that they really need 720 count resolution on a real robot ... and I'll be happy to look at PRs

**Comment by dlech** [comment]
As already discussed, the advantage would be better motor control at low speeds, but, yeah, that's about it. 

So, if anyone has an actual use case for this, speak up. Just saying "it is a good idea" without a concrete reason won't convince us.

**Comment by cho934** [comment]
Very good idea for a best asservissement like this:
http://rcva.fr/index.php?option=com_content&view=article&id=18:cours-asservissement&catid=8:les-cours&Itemid=34

It is important to have precision.

Few information using 360 ticks resolution
1) if I use caterpillars or small wheels (around 40mm diameter)
I obtain here a precision of 0.349 mm per tick
with a max speed of 860 ticks/s = 300mm/s

2) if I use large lego wheels (78mm diameter)
I obtain a precision of 0.698 mm per tick
with a max speed of 600mm/s
So here, speed is bigger but I lose precision (to turn around for example, 89° instead of 90° and the robot miss its destination... )

And it will be the same using external encoders to avoid slippage (using HT-nxt-angle for example), Moreover external must be more precise than motorisation encoders. 

So double encoders precision will be an advantage for all type of encoders ;)

**Comment by cho934** [comment]
Just saying "it is a good idea" with 2 videos:

1) lego robot using this asservissement (with 360 counts)
https://www.youtube.com/watch?v=3ge9Rb7Ptdw

2) RCVA and OmyBot robots using more than 1000 counts per rotation in their encoders (and also a good program)
https://www.youtube.com/watch?v=iH2otmdrsXA

You can watch others videos in my channel ;)

**Comment by cho934** [comment]
We have just participate to the French Cup of Robotics last week, and I can confirm that our motor control with only 360 counts per rot is not enough to have a good precision of the odometry. I discussed with several best teams, and they usually used 1024 or 2048 counts encoders.

Do you think it is possible to have a double precision also on the HT-nxt-angle ?

;)

**Comment by dlech** [comment]
They are obviously not using LEGO motors. The LEGO motors have about 4 or 5 degrees of slop. That means I can turn the motor +/- 2 degrees without the position encoder changing at all. This is because there are many gears in between the shaft of the motor and where the encoder is. So even if we double the encoder precision, the motor can still travel 2 or 3 degrees without the change being measured and you will still have the same odometry problems.

What you need is a high precision encoder attached directly to the axle of your wheels. And no, we can't double the precision of the HT NXT Angle sensors. The mindsensors.com [GlideWheel sensor](http://www.mindsensors.com/ev3-and-nxt/17-glidewheel-as-angle-sensor-for-nxt-or-ev3) has 0.5 degree precision, so would be a better choice than the HT angle sensor. If you want higher precision than that, you will probably have to design your own sensor.

Of course, there are other ways of getting around too. Gyros, LIDAR, light sensors, etc.

**Comment by dlech** [comment]
I found a firmware that has double encoder precision. It would be interesting for someone to try it and perform an experiment to see if there is actually a measurable difference in the amount of control you get in the motor. http://icube-avr.unistra.fr/en/index.php/EV3.14

**Comment by dlech** [comment]
This is essentially now done in ev3dev-stretch. See https://github.com/ev3dev/ev3dev/issues/853#issuecomment-403341872. However, it was noted that the tacho counts are not evenly spaced, so while this technically does increase "precision", trying to use these values actually makes for less "accuracy". For example, one count might be 1/3 of a degree and the next count 2/3. Having these unevenly spaced counts messes up speed calculations, so we are using every 4th count to get an accurate speed measurement.

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/wiki/Internals%3A-ev3dev-stretch#pru-quadrature-encoder
