### ISSUE TITLE
Problem on access pwm pins on sysfs

### ISSUE THREAD

**Issue by juliovendramini** [ev3dev/ev3dev#1627]
Hi, I'm tring to using pwm pins on motor ports of EV3 to control RC servos.
But when I tried to export de pwm pins I get this error:
![image](https://github.com/ev3dev/ev3dev/assets/47861761/5b5078e3-bad7-42d3-9b8b-273852b0d9f0)
The only pwm I could export was pwm0 from pwmchip3. But on pwm0 I got error when try do change paramters
Before try that, I put the ports on RAW mode.
I tried to disable the ports on DTC file too, and I got the same error.

I don't know what I'm doing wrong. Can you help me?

Big Thanks.

**Comment by dlech** [comment]
Since the PWMs go through the motor driver chip and give battery voltage instead of 5V DC, they aren't really suited for the typical RC servo motors. I would suggest something like http://www.mindsensors.com/ev3-and-nxt/25-8-channel-servo-controller-for-nxt-or-ev3 to connect these type of motors to ev3dev. We even have a driver for it already. http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/motors.html#servo-motor-subsystem

**Comment by juliovendramini** [comment]
Thanks for the sugestion, we Alread use sensor port to control servos. Here we use a PCA9685 driver to control over 16 servos.
The problem using this sollution is that it's use a sensor port and are quite large. And we haven't a sensor port available.
But, motor port we have. I alread look the schematic of lego ev3, I know that I need to put a voltage divider with resistor, and I think that the H-bridge will support 50hz pwm.
My Idea is to set the control pins to input and use the pwm pin to output same value on two power pins of the motor port
Our main problem is the size of the robot, this if why we are trying this instead of use lego medium motors.
![image](https://github.com/ev3dev/ev3dev/assets/47861761/f9ec8082-649c-4980-9cab-2a0ab350622c)

**Comment by dlech** [comment]
I would use one of the ECAP PWMs. They only have a single channel. See https://www.ev3dev.org/docs/kernel-hackers-notebook/ev3-pwm/

The PWM that you exported is the unconnected one and setting the period failed because both output channels on the chip need to have compatible periods.

Before you can export on of the PWM channels to sysfs, you will need to unbind the port driver that is using it.

**Comment by juliovendramini** [comment]
Hi, thanks!
It's worked!!
After unbind the driver, I put
* one of the pins with:
   * direction OUT 
   * value 0
 * the other one:
    * direction IN
    
So, that pin with direction IN will be controller with pwm pin. 
On the datasheet of LB1836M said that two pins with LOW value will left float the output  pins, but with the voltage divider it's not a problem, because it made a pulldown resistor, and it's work.

Thanks again!

**Comment by dlech** [comment]
Glad to hear it is working!
