### ISSUE TITLE
Add some sort of a brickman "terminal mode"?

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#173]
Now that we have brickman, I have been finding myself in an interesting situation while working on the EV3. I want to execute some commands in the terminal, but don't want to fully exit brickman to do so.

I was thinking that if there was a "terminal mode", where brickman would let you use a terminal but easily go back to the GUI with a "back" button press, I think it could be quite useful. Maybe one could even use the onscreen keyboard if it was a quick command. Past that, having the terminal session run through brickman could allow larger text sizes, maintaining the status bar at the top, etc.

**Comment by dlech** [comment]
I'm closing this as `wontfix` since there are existing programs that will let you do this. For example you can use `openvt` to run a program in a new virtual terminal. You can also use `chvt` to switch virtual terminals and `conspy` to control a virtual terminal remotely. I am including `conspy` in the next release and the other commands are already installed by default.
