### ISSUE TITLE
SSH server is not running on ev3dev-jessie-2014-10-07

### ISSUE THREAD

**Issue by OpenHelios** [ev3dev/ev3dev#216]
After booting ev3dev, I connect my keyboard via USB, switch to terminal with CTL+ALT+F1, and login with root and r00tme. Then I start
  ssh -l root 127.0.0.1
but it does not work. Starting the server with
  systemctl start ssh
and showing the result with
  systemctl -l status ssh
shows, that something with the keys seams to be wrong. In the folder /etc/ssh/ there are some key files with 0 size, which could be a hint.

**Comment by dlech** [comment]
Haven't had any reports of this in a while, so closing. We can re-open if the issue comes up again.

**Comment by dlech** [comment]
It looks like I didn't close this when I said I was going to, but it is just as well. This has come up a few times recently. I noticed that RPi ships the same host keys always. This is actually not a bad idea since we really aren't too concerned about security here. It would have the advantage that you won't get scary warning messages each time you flash the SD card. Advanced users can of course generate new host keys if they like.

**Comment by dlech** [comment]
Fix has been released in the ev3dev nightly images starting on 2016-07-19

[ ![Download](https://api.bintray.com/packages/ev3dev/nightly/ev3dev-jessie/images/download.svg) ](https://bintray.com/ev3dev/nightly/ev3dev-jessie/_latestVersion)
