### ISSUE TITLE
Detecting Firgelli L100 and Stall

### ISSUE THREAD

**Issue by MetallianFR68** [ev3dev/ev3dev#224]
Hello,

Is there a way to detect a Firgelli L100 actuator ?
It's type attribute is "tacho-motor".
No way to differentiate it from an EV3 LARGE MOTOR
I would like to implement autodetection to autoset the position limits

Other question : is there a way to implement stall detection for the L100 ?
When the L100 reaches it's limit, the motor doesn't stop, stays in ramp_const status, and can't receive new instructions.

Bonus question:
When I plug, unplug, replug a motor, the index changes from sys/class/tacho-motor/motor0 to sys/class/tacho-motor/motor1
My PHP script, which is configured to control motor0, stops working then.
Is there another path somewhere that doesn't change when you unplug a motor ?
For example some path attached to the PORT instead ?
Like /sys/class/portA/motor ?

**Comment by dlech** [comment]
For stall detection, see #455.

**Comment by dlech** [comment]
This fix has been released in the `3.16.7-ckt26-10-ev3dev-ev3` kernel (and other `10-ev3dev` kernels on other platforms). Be aware the tacho-motor class has breaking changes in this release, so don't expect motors to work with your existing programs/libraries if you upgrade to this version.

As this issue is quite old, if there are further comments related to this subject, please open a new issue.
