### ISSUE TITLE
Lua binding help wanted

### ISSUE THREAD

**Issue by Svetomech** [ev3dev/ev3dev#288]
How do I actually run .lua files on the brick? I have established SCP connection, copied "https://github.com/ev3dev/ev3dev-lang/blob/develop/lua/RemoteControl-test.lua" to my home user directory but when trying to run it I always get an error about not having "ev3dev" package. Okay, I placed ev3dev.lua, class.lua and drive.lua to my lua 5.2 share directory. Still not working, it shows me something like "device not connected". The problem line is "r = RemoteControl()".

And yes, I have my EV3 Infrared Sensor connected to the device, it is even visible in Device Browser of the brickman menu.

I suppose I'm getting this error (from ev3dev.lua file):

function Device:setAttrInt(name, value)

  if (self._path == nil) then
    error("no device connected")
  end
...

But why?

**Comment by dlech** [comment]
The lua library is out of date and the original developer has been busy with life and has not had time to update it for more recent changes in the kernel drivers. This is basically the same issue in #265, which is why I marked this as duplicate. There is more information in #265 about what needs to be done to update the lua bindings.
