### ISSUE TITLE
tacho-motor/*/hold_pid/* properties are not readable

### ISSUE THREAD

**Issue by ddemidov** [ev3dev/ev3dev#314]
The documentation [says](https://github.com/ev3dev/lego-linux-drivers/blob/282b76e91932dbc3887691f45432399e782ac18e/motors/tacho_motor_class.c#L103-L110) that the properties are read/write, but reading those results in an error:
```
cat /sys/class/tacho-motor/motor0/hold_pid/Kp
cat: /sys/class/tacho-motor/motor0/hold_pid/Kp: Operation not supported
```
See also https://github.com/ev3dev/ev3dev-lang/issues/53.

**Comment by dlech** [comment]
If an attribute does not have read or write access, you will get a permission error (`-EACCESS` I think) rather than an operation not supported error (`-EOPNOTSUPP`). This is working as indented. Reading and writing the hold_pid parameters for the `legoev3-motor` driver is not implemented, thus the `-EOPNOTSUPP` error. When using the `ms-nxtmmx` driver, these attributes will actually do something.

So, this is working as intended.
