### ISSUE TITLE
Samples do not work

### ISSUE THREAD

**Issue by burf2000** [ev3dev/ev3dev#407]
Just got the latest EV3Dev, updated etc

root@ev3dev:~# echo run-forever > $MC/command
-bash: /sys/class/tacho-motor/motor2/command: No such file or directory

What ever command I run I get
/sys/class/tacho-motor/motor2/duty_cycle_sp: No such file or directory

**Comment by dlech** [comment]
Are there any devices listed in the device manager on the EV3?

You can also see a list of all motors by running `ls /sys class/tacho-motor/`.

**Comment by burf2000** [comment]
Yes 2 Ev3 motors (plus 2 pf motors connected but not listed)

**Comment by dlech** [comment]
The device manager will tell you the name `motorX` which translates to `/sys/class/tacho-motor/motorX`. Since you only have two motors showing up, my guess is that they are `motor0` and `motor1`, not `motor2

**Comment by dlech** [comment]
Dang. Accidentally posted somehow. Continuing...

...not `motor2` as in your original comment. Also, power functions motors can't be automatically detected, which is why they are not showing up. You have to manually set the mode of the port. You can do this on the brick in the *Device Manager* under *Ports* or programmatically with `/sys/class/lego-port/portX`.

**Comment by rhempel** [comment]
Dave, you can edit your posts :-) I do it all the time.

**Comment by G33kDude** [comment]
Ah, but it doesn't send an email notification about the edit does it?

**Comment by rhempel** [comment]
Maybe not, but if you catch the edit within a couple of minutes, how likely is that the post has been read...

**Comment by G33kDude** [comment]
Email notifications send the body of the comment with the notification, so if someone's following the thread via email, pretty much 100%

**Comment by dlech** [comment]
Motor drivers have had a major overhaul since this issue was opened. Please open a new issue for any similar problems.

**Comment by sudharsh** [comment]
I have a similar issue where none of the run-* command work. However am able to query the speed of the motor without problems. I guess this means that the driver was loaded successfully.

Is there a way I can debug this?

The `state` of the motor seems to be empty as well.

**Comment by dlech** [comment]
As I mentioned in my previous comment, please open a new issue instead of continuing to post on this closed issue. Also, we can't help you if you don't tell us exactly what you tried.

**Comment by sudharsh** [comment]
Ok. Will do that






On Thu, Apr 14, 2016 at 8:26 AM -0700, "David Lechner" <notifications@github.com> wrote:












As I mentioned in my previous comment, please open a new issue instead of continuing to post on this closed issue. Also, we can't help you if you don't tell us exactly what you tried.
