### ISSUE TITLE
Adding webcam on the Robot

### ISSUE THREAD

**Issue by jsvalderrama** [ev3dev/ev3dev#64]
Hello, 

I am trying to install a Logitech webcam on my robot and I have been encountering several problems. I am wondering if you could help me on this ? 

I am using the driver Logitech Quickcam Notebookls with the following instructions: http://qce-ga.sourceforge.net/

Could you please tell me if it’s possible to make it work? I would really appreciate to have this cam working on my project.

Thanks in advance for you answer.
I join the log that I have during the subsequent steps, but it seems that there is a Kernel problem looking for X86 build. What can be the workaround?

```
[!] Kernel configuration file /lib/modules/3.3.0-1-ev3dev/build/.config not fou$
If the headers have been already configured properly, you might
not need it. But it would be better not to trust this, you
really should know where is your configuration file, and
copy it into its place. Often it can be found in /boot/
directory with a name like /boot/config-2.4.26 or something.
WARNING: If you press Enter, I'll try to continue anyway,
but this probably will fail. You SHOULD press Ctrl+C now.
Press Ctrl+C to quit, Enter to continue --->
[!] Can not find version.h in kernel source.
[!] Kernel source is not configured properly.
You have only kernel headers but they are not configured
properly. It's pointless trying to continue, this won't work.
Either install properly configured kernel headers or full
source with kernel configuration file. In the latter case
I can configure the kernel source using the configuration
file automatically.
```

**Comment by chad3814** [comment]
@fdetro did you have to cross-compile motion on another machine, or is there an apt repo I can add that has the armv5 binaries?

**Comment by dlech** [comment]
There is an official debian package for motion.

    sudo apt-get update
    sudo apt-get install motion

**Comment by chad3814** [comment]
must've been the update, I had tried before. thanks

**Comment by obo** [comment]
First of all thanks for the fabulous ev3dev!
I think this old issue is perhaps the best place to ask.

I am very new to both ev3dev and v4l. I am trying to get my old Logitech camera work with my brand new EV3.
The problem is that /dev/video0 is not created for me and the kernel module is not available. Here is some diagnostics I was able to gather:

lsusb
Bus 001 Device 003: ID 046d:08ae Logitech, Inc. QuickCam for Notebooks

sudo hwinfo --usb
04: USB 00.0: 11200 TV Card
  [Created at usb.122]
  Unique ID: ADDn.elweGVRLXdD
  Parent ID: k4bc.BtRjRTLQ986
  SysFS ID: /devices/platform/ohci.0/usb1/1-1/1-1:1.0
  SysFS BusID: 1-1:1.0
  Hardware Class: tv card
  Model: "Logitech Camera"
  Hotplug: USB
  Vendor: usb 0x046d "Logitech, Inc."
  Device: usb 0x08ae "Camera"
  Revision: "1.00"
  Speed: 12 Mbps
  Module Alias: "usb:v046Dp08AEd0100dc00dsc00dp00icFFiscFFipFFin00"
  Driver Info #0:
    Driver Status: zc0301 is not active
    Driver Activation Cmd: "modprobe zc0301"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #3 (Hub)

dmesg
[ 4957.057832] usb 1-1: USB disconnect, device number 2
[ 4968.794243] usb 1-1: new full-speed USB device number 3 using ohci
[ 4969.013560] usb 1-1: New USB device found, idVendor=046d, idProduct=08ae
[ 4969.013649] usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 4969.013705] usb 1-1: Product: Camera

sudo modprobe zc0301
modprobe: FATAL: Module zc0301 not found.

According to this list (http://mxhaard.free.fr/spca5xx.html), the camera should be supported by the old spca5xx which is supposedly already in the kernel. I have no idea what is the relation between zc0301 and spca5xx.

For completeness:
uname -a
Linux ev3dev 4.4.87-22-ev3dev-ev3 #1 PREEMPT Sat Sep 9 14:45:55 CDT 2017 armv5tejl GNU/Linux

Any ideas what to try to get the camera correctly recognized?

**Comment by dlech** [comment]
> I think this old issue is perhaps the best place to ask.

closed issues are rarely a good place to make new comments (unless you are asking to re-open the issue)



> sudo modprobe zc0301
> modprobe: FATAL: Module zc0301 not found.

It looks like this uses the same kernel module mentioned in #1030. It will be available in the next kernel release. You can subscribe to that issue to be notified when that happens.

**Comment by obo** [comment]
Thanks for the correct pointer. Yes, it seems that #1030 will resolve my problem.
Staying tuned. :-)
Thanks! Ondrej.

----- Original Message -----
> From: "David Lechner" <notifications@github.com>
> To: "ev3dev/ev3dev" <ev3dev@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Comment" <comment@noreply.github.com>
> Sent: Sunday, 22 April, 2018 01:32:34
> Subject: Re: [ev3dev/ev3dev] Adding webcam on the Robot (#64)

>> I think this old issue is perhaps the best place to ask.
> 
> closed issues are rarely a good place to make new comments (unless you are
> asking to re-open the issue)
> 
> 
> 
>> sudo modprobe zc0301
>> modprobe: FATAL: Module zc0301 not found.
> 
> It looks like this uses the same kernel module mentioned in #1030. It will be
> available in the next kernel release. You can subscribe to that issue to be
> notified when that happens.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ev3dev/ev3dev/issues/64#issuecomment-383341257

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by dlech** [comment]
I actually just pushed a new snapshot image that includes this fix a few minutes ago if you would like to try it out.

https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2018-04-22/

**Comment by obo** [comment]
I'd prefer to just apt-get update, not to reflash the SD card. Is the new kernel available to apt-get?

(Or is it common that people reflash and re-populate SD cards frequently?)

Thanks, O.

----- Original Message -----
> From: "David Lechner" <notifications@github.com>
> To: "ev3dev" <ev3dev@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Comment" <comment@noreply.github.com>
> Sent: Sunday, 22 April, 2018 23:32:59
> Subject: Re: [ev3dev/ev3dev] Adding webcam on the Robot (#64)

> I actually just pushed a new snapshot image that includes this fix a few minutes
> ago if you would like to try it out.
> 
> https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2018-04-22/
> 
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ev3dev/ev3dev/issues/64#issuecomment-383414081

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by dlech** [comment]
apt upgrade only works if you are using an ev3dev-stretch image already. If you are using ev3dev-jessie, then you need to re-flash the SD card.

**Comment by obo** [comment]
I'm still on jessie, so I'll try reflashing.
I guess the bluetooth connection setup and the robot@... password are the same.
(By the way, for some strange reason, I always have to remove and pair again, otherwise the bluetooth connection won't work. I'll see if ev3dev-stretch is better in this respect and file a new issue once I diagnose it better.)
Thanks,
  Ondrej.

----- Original Message -----
> From: "David Lechner" <notifications@github.com>
> To: "ev3dev" <ev3dev@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Comment" <comment@noreply.github.com>
> Sent: Sunday, 22 April, 2018 23:46:05
> Subject: Re: [ev3dev/ev3dev] Adding webcam on the Robot (#64)

> apt upgrade only works if you are using an ev3dev-stretch image already. If you
> are using ev3dev-jessie, then you need to re-flash the SD card.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ev3dev/ev3dev/issues/64#issuecomment-383414875

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by obo** [comment]
Having tried snapshot-ev3dev-stretch-ev3-generic-2018-04-22.img.xz, I still have no luck with the camera.

The messages now are:

dmegs:
[ 2498.040488] usb 1-1: new full-speed USB device number 2 using ohci-da8xx
[ 2498.310741] usb 1-1: New USB device found, idVendor=046d, idProduct=08ae
[ 2498.310804] usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 2498.310840] usb 1-1: Product: Camera         
[ 2499.162313] usbcore: registered new interface driver snd-usb-audio

lsusb
Bus 001 Device 002: ID 046d:08ae Logitech, Inc. QuickCam for Notebooks

uname -r
4.14.34-ev3dev-1.6.1-ev3

sudo modprobe zc0301
modprobe: FATAL: Module zc0301 not found in directory /lib/modules/4.14.34-ev3dev-1.6.1-ev3

I don't have hwinfo and due to #925, I can't connect the robot to the internet to install it easily. What else could I try to diagnose the camera problem with this stretch build?

Thanks, O.

**Comment by dlech** [comment]
please open a new issue for this problem
