### ISSUE TITLE
EVB FATCATLAB sensor support

### ISSUE THREAD

**Issue by kortschak** [ev3dev/ev3dev#654]
I've just done a survey of FATCATLAB sensors work (none is mentioned in the supported sensors list, so I wasn't expecting great success).

Install from evb-ev3dev-jessie-2016-01-25.img, kernel at 4.4.9-ti-rt-r25-11-ev3dev-bb.org.

Three sensors work out of the box: altitude, gesture and humidity.

Two sensors are not detected: light sensor and IR receiver.

Two sensors appear to crash Brickman: 9DOF sensor and ADC adapter. They can be seen via the sysfs, but only the first device attached will register, subsequent devices fail to load and devices that are removed are not unloaded. The device cannot be shutdown from the command line after either of these devices has been attached.

The behaviour is pretty much the same when these sensors are attached to an EV3 with the exception that Brickman is not crashed (I need to look at `/sys/class/lego-sensor` in this case - not yet done).

I'm happy to try to pick some of these up, but again I'm likely to need some help/pointers, since the last drivers I worked on were I2C not UART.

**Comment by dlech** [comment]
I don't think most people realize this, but this but LEGO did a decent job designing the UART sensors. The sensors send all the information that you need to use the sensors, so you don't have to write a driver for each sensor. You just plug them in and they work.

I'm guessing that the problems you are seeing are some deviations from the official LEGO firmware. Unfortunately, Andy Lau and his fat cat have been MIA since January 2015 and no one has been able to get their hands on the EVB firmware source code. So, we will have to do some reverse engineering.

This will be easiest if you have a logic analyzer. By attaching it to pins 5 and 6, we can monitor what the sensors is sending and see if it is something the driver knows how to handle or not.

If you don't have a logic analyzers, you can at least check `dmesg` for related messages. You can also do some `printk` debugging, but I have found this troublesome with UART sensors because they receive data much faster than it can be printed out. The driver in question is <https://github.com/ev3dev/lego-linux-drivers/blob/master/sensors/ev3_uart_sensor_ld.c>.

> subsequent devices fail to load and devices that are removed are not unloaded.

I have actually already fixed this problem, but have not released an updated package. It also looks like I forgot to push the change to GitHub and I'm away from my main dev computer for the weekend, so this will have to wait. Ping me on Tuesday if I haven't done anything on this yet.


And finally, when we get these working, we will need to put a big disclaimer on the sensors page on the website that "these sensors do not work with BrickPi, PiStorms or the mindsensors.com EV3 sensor adapter". These 3rd party devices have EV3 sensors hard coded and only know about the four LEGO brand sensors. It is not technically possible to get them working with these devices without a firmware update. These devices use <https://github.com/ev3dev/lego-linux-drivers/blob/master/sensors/ev3_uart_sensor_core.c> and <https://github.com/ev3dev/lego-linux-drivers/blob/master/sensors/ev3_uart_sensor_defs.c>. Do not add the FatcatLab sensors to these files. They will not work.

Instead, we should add them to <https://github.com/ev3dev/lego-linux-drivers/blob/master/sensors/other_sensor_defs.c> or a new `*_defs.c` file to generate documentation for the website.

**Comment by kortschak** [comment]
Tangentially related, how do I attach a serial interface to the EVB?

**Comment by dlech** [comment]
http://botbench.com/blog/2013/08/15/ev3-creating-console-cable/

**Comment by dlech** [comment]
You have to solder on some male (3x1) and female (6x1) header. I recommend low-profile female header. I hacked an old DIP socket to use a female header on mine.

![img_20160531_111728](https://cloud.githubusercontent.com/assets/963645/15682157/fc76b740-2721-11e6-85ee-c7c51fba1587.jpg)
![img_20160531_111704](https://cloud.githubusercontent.com/assets/963645/15682182/147a4de8-2722-11e6-8e7b-90aadc5c995d.jpg)

**Comment by dlech** [comment]
If you don't crash the kernel, `dmesg -w` in a second terminal window works just as well as a serial console.

**Comment by dlech** [comment]
> subsequent devices fail to load and devices that are removed are not unloaded.

This is fixed in `evb-systemd 3`. Please upgrade that package.

**Comment by dlech** [comment]
> Two sensors appear to crash Brickman

Please open a new issue for this and post the output of `sudo systemctl status -l brickman.service`

**Comment by kortschak** [comment]
>If you don't crash the kernel, `dmesg -w` in a second terminal window works just as well as a serial console.

Yes, I think I'll do that for now.

**Comment by kortschak** [comment]
```
robot@ev3dev:~$ dpkg -l evb-systemd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  evb-systemd    3            armhf        Systemd unit files and udev rules
```

Same outcomes. I'll file another couple of issue.

**Comment by kortschak** [comment]
Sorry, it seems to be sporadic now.

**Comment by dlech** [comment]
I think we have most of these working now. Can this issue be closed?

**Comment by kortschak** [comment]
Yes. Thanks.
