### ISSUE TITLE
Stuck at ev3dev booting flash...

### ISSUE THREAD

**Issue by chris-xstem** [ev3dev/ev3dev#655]
### System information:

* I am using: *LEGO MINDSTORMS EV3*

* I installed ev3dev using this image file: *ev3-ev3dev-jessie-2015-12-30.img*

* My kernel version is: *...DO NOT KNOW...*

* My host computer is running: *OS X*

* I am connecting using: *USB*

### About my issue:

While booting, I can see the "ev3dev booting" flash, however, it stays there... for hours ....

Not sure what I can do to trouble shoot, I have tried these tips:
![image](https://cloud.githubusercontent.com/assets/18240977/15628060/aa9873cc-2529-11e6-8238-b4a748749f7f.png)

But it still stuck at the booting flash screen.

**Comment by dlech** [comment]
Did you actually try a different SD card?

The only way to actually figure out where it is getting stuck it so attach a USB serial adapter to input port 1 and look at the output there.

**Comment by JorgePe** [comment]
This also happens frequently with one of my EV3, usually the two-button reset doesn't work and I need to take LiPo battery out, then it always boots immediately after.
Since this is a SD card I've been using at least more than an year (apt-get update + upgrade + dist-upgrade) and the other EV3 is OK with a fresh SD card with the latest (December?) image I never cared much, thinking it  maybe just a bug from previous versions.

**Comment by chris-xstem** [comment]
OK…

Going to try the "USB serial adapter”.

Chris.Chen @ XSTEM EdFun
4 ~ 6, ZHENHUA ROAD, BAOSHAN DISTRICT, SHANGHAI, CHINA
Tel: +8621.5620.6698 <>
Phone: +86138.1783.4205 <>

**Comment by dlech** [comment]
If this is still not working, please try the latest "nightly" build.

[ ![Download](https://api.bintray.com/packages/ev3dev/nightly/ev3dev-jessie/images/download.svg) ](https://bintray.com/ev3dev/nightly/ev3dev-jessie/_latestVersion)

**Comment by Fuzzyma** [comment]
@dlech the link you provided is not valid. I would like to try the nightly build. Where can I get it?

**Comment by dlech** [comment]
Please re-open if this is still an issue with the latest image.
