### ISSUE TITLE
Edimax WIFI not working on kernel 4.4.13

### ISSUE THREAD

**Issue by Zordid** [ev3dev/ev3dev#694]
Hi!
Sorry for opening a new issue on this, but you are connecting various issues and say "fix commited" or "duplicate of" - but none of this is true.

Just a short recap: I got the Edimax WiFi dongle that worked flawlessly with the kernel that comes in the latest image (december).

Updating to the kernel version 12 made this instable - this is meant by my own issue https://github.com/ev3dev/ev3dev/issues/669

That one was closed and tagged "fix committed".

Now: starting with a fresh image from ev3-ev3dev-jessie-2015-12-30.img and afterwards upgrading the kernel to v13 NOTHING works anymore with this dongle type.

This is absolutely a desaster. :(

Can someone explain why these issues were tagged duplicates of one another and why they were closed?

From my current situation: nothing is fixed. :(

**Comment by dlech** [comment]
In the future, if you think we should re-open an issue because it is not fixed, please make a comment on the closed issue.

However, Issue #669 has not been closed. "fix committed" only means that we have committed the fix in the source code. The commit is <https://github.com/ev3dev/ev3-kernel/commit/65ab378bb12a23b3b5b62afe4d0c7d91acc34179>.

I have tagged the other issues (and this issue) as duplicates because there should only be one place to keep all of the relevant comments on an issue. If the comments are spread out on 4 different issues, then it makes them hard to find.

If you cannot wait for the next kernel release, then you can build your own kernel. I have already explained this in <https://github.com/ev3dev/ev3dev/issues/693#issuecomment-230166566> which goes to show why duplicate issues are a problem because all of the information is not in one place. You could also just not upgrade the kernel until a fix is released.
