### ISSUE TITLE
Gitter Topics

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#769]
Something new to play around with...

gitter.im is developing a new forum-like feature. Try it out at <https://gitter.im/ev3dev/topics>.

**Comment by WasabiFan** [comment]
Ooh, that looks cool!

**Comment by dwalton76** [comment]
I made a testing123 topic...does gitter link back to the ev3dev github repo somehow?

**Comment by WasabiFan** [comment]
What do you mean? I see your topic and it lets me reply to it, but there doesn't seem to be much integration. It's pretty much just a separate forum.

**Comment by dwalton76** [comment]
It made me grant access from my github account and I'm trying to figure out why

**Comment by dwalton76** [comment]
On a related note has slack been considered for this sort of thing?

**Comment by WasabiFan** [comment]
Why would we use Slack? It's functionally the same as Gitter, except that Gitter is free for public use while Slack is the inverse.

**Comment by dwalton76** [comment]
slack is free unless you want to archive more that 10k messages, I imagine it would take us a long time to hit that limit (and would we care if we did).  I mention slack because it is pretty easy to use and it does integrate with github.

**Comment by WasabiFan** [comment]
We have a Gitter account (with a general room) [here](https://gitter.im/ev3dev/chat/). Gitter is built specifically for GitHub, so it has integration at a deeper level than Slack. Gitter is also completely free and unlimited for public use, meaning that anyone can follow a link to ask us questions in the chat room. Slack, on the other hand, is only free as you mentioned for _private_ use; that means that maintainers could be added but it wouldn't work as a place to chat with users. It also requires a separate GitHub plugin, meaning you don't get automatic GitHub links or snapped log.

I work with both services on an hourly basis, so I know how they work. We use Gitter because it serves the specific purpose that we needed.

The topic of this issue is a new feature called _Topics_; this feature adds a public forum to Gitter. This is separate from standard chat and something that Slack does not have.

**Comment by dwalton76** [comment]
From the ev3dev repo here how do I see the testing123 topic that I created in gitter...or is it only integrated from github->gitter but not gitter->github?

**Comment by dwalton76** [comment]
I'm not saying I'm against Gitter, I'm just trying to understand exactly how it integrates with github.

**Comment by dlech** [comment]
You can't see anything from gitter on the github site. You can see stuff from github on the gitter site though.

**Comment by WasabiFan** [comment]
It's also important to understand that the "testing123" topic is a _Topic_, which is a beta feature only recently introduced. The primary functionality of Gitter is standard chat.

**Comment by dlech** [comment]
It doesn't seem that this ever really took off.
