### ISSUE TITLE
Hi! I didn't find ability to put Hi-Technic Color Sensor V2 in passive mode (sensor led turns off) seen in EV3-G. Is there a way to do this?

### ISSUE THREAD

**Issue by nikmachines** [ev3dev/ev3dev#920]

**Comment by dlech** [comment]
Can you post a picture of the EV3 block? I don't see anything at http://www.hitechnic.com/cgi-bin/commerce.cgi?preadd=action&key=NCO1038 that indicates that you can turn the LED off. However, https://github.com/botbench/robotcdriversuite/blob/master/include/hitechnic-colour-v2.h does mention a "passive mode" command, but it is not clear that this turns off the LED.

**Comment by nikmachines** [comment]
Here it is. In EV3-G passive mode turns led off.
![htsensor](https://user-images.githubusercontent.com/25134321/28511537-79f3351c-706f-11e7-94da-3a98b55acd46.jpg)

**Comment by dlech** [comment]
When you select passive, what are the outputs? Just red, green, and blue or something else?

**Comment by dlech** [comment]
I added a `PASSIVE` mode in the `21-ev3dev` kernel. I don't have this sensors, so I have no idea if it works or not, but you can try it out.

**Comment by nikmachines** [comment]
PASSIVE mode does not power led off... White output (slight blue tint), as usual.

**Comment by dlech** [comment]
As far as I can tell, we are doing exactly what the EV3-G block does. Here are the internals:

![cq8l9zzkhm](https://user-images.githubusercontent.com/963645/28724290-1f33207a-737f-11e7-9cc5-a2ec75cf7639.png)

![ddv3uyf8gt](https://user-images.githubusercontent.com/963645/28724398-71aab2be-737f-11e7-8a80-45543dd66c66.png)

It looks like I did make a mistake with the data type though. It should be 16-bit instead of 8-bit.

If you are absolutely sure that passive mode does indeed turn off the LED, the someone with a logic analyzer will need to take a look at what is actually going over the wires. If someone wants to send me one of these sensors (for keeps), I can do it.

**Comment by nikmachines** [comment]
Sorry, i was wrong - it seems to be working (kernel wasn't updated)! Led is definitely off in "PASSIVE" mode :)
